# Generated by Django 5.2.7 on 2025-11-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
